stages:
  - install_dependencies
  - build

behaviortree_cpp:
  stage: install_dependencies
  image: grupoavispa/behaviortree_cpp:4.6
  script:
    - echo "Getting BehaviorTree.CPP"
    # Copy include and lib directories to the CI_PROJECT_DIR (to be able to use them in the next stage)
    - mkdir -p $CI_PROJECT_DIR/artifacts/include
    - mkdir -p $CI_PROJECT_DIR/artifacts/lib
    - cp -r /usr/local/include/ $CI_PROJECT_DIR/artifacts
    - cp -r /usr/local/lib/ $CI_PROJECT_DIR/artifacts
  artifacts:
    paths:
      - artifacts/
    expire_in: 15 min

build:
  stage: build
  image: grupoavispa/cortex:development-latest
  dependencies: [behaviortree_cpp]
  before_script:
    - DEBIAN_FRONTEND=noninteractive apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -y cmake make build-essential libboost-all-dev nlohmann-json3-dev
  cache:
    key: cache-${CI_COMMIT_REF_SLUG}
    fallback_keys:
      - cache-${CI_DEFAULT_BRANCH}
    paths:
      - build/
  script:
    - echo "Copying dependencies"
    - cp -r artifacts/* /usr/local/
    - echo "Building project"
    - mkdir -p build && cd build
    - cmake ..
    - make -j$(nproc)
    - make install