# GitHub Actions workflow to build WASP DSR Planner

name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  install-behaviortree-cpp:
    name: Install BehaviorTree.CPP
    runs-on: ubuntu-24.04
    container:
      image: grupoavispa/behaviortree_cpp:4.6
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Cache dependencies
        id: cache-btcpp
        uses: actions/cache@v4.2.0
        with:
          path: |
            /usr/local/include
            /usr/local/lib/libbehaviortree_cpp*
          key: behaviortree-cpp-${{ runner.os }}-ubuntu-24.04

  build:
    name: Build Project
    runs-on: ubuntu-24.04
    container:
      image: grupoavispa/cortex:development-latest
    needs: install-behaviortree-cpp
    steps:
      - name: Update APT
        run: |
          DEBIAN_FRONTEND=noninteractive apt-get update -y
          DEBIAN_FRONTEND=noninteractive apt-get install -y make cmake build-essential libboost-all-dev nlohmann-json3-dev libzmq3-dev

      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Restore BT cache
        id: restore-cache-btcpp
        uses: actions/cache@v4.2.0
        with:
          path: |
            /usr/local/include
            /usr/local/lib/libbehaviortree_cpp*
          key: behaviortree-cpp-${{ runner.os }}-ubuntu-24.04

      - name: Build project
        run: |
          ls -la
          mkdir -p build && cd build
          cmake ..
          make -j$(nproc)
          make install
